In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("retail_sales.csv")
df.head()

,OrderID,OrderDate,ShipDate,ShipMode,Channel,CustomerID,CustomerName,Email,Phone,Age,...,UnitPrice,Discount,PromoCode,Sales,Cost,Profit,ProfitMargin,PaymentMethod,SalesRep,Returned
0,ORD-1005371,2021-01-01,2021-01-06,Standard,Phone Order,CUST-104055,Chloe Nguyen,chloe.nguyen5@outlook.com,+1-727-573-1855,51,...,130.75,0.05,NEWYEAR,993.70,577.76,415.94,41.86,Debit Card,Jessica A.,No
1,ORD-1005791,2021-01-01,2021-01-07,Standard,Online,CUST-101234,Richard Gonzalez,richard.gonzalez57@hotmail.com,+1-647-352-2293,40,...,185.55,0.15,NEWYEAR,157.72,130.39,27.33,17.33,Apple Pay,Ananya D.,No
2,ORD-1008078,2021-01-01,2021-01-07,Standard,Phone Order,CUST-105358,Barbara Smith,barbara.smith1996@proton.me,+1-500-343-1036,56,...,40.12,0.00,NaN,40.12,19.63,20.49,51.07,Debit Card,Liam C.,No
3,ORD-1009062,2021-01-01,2021-01-08,Standard,Phone Order,CUST-103845,Sarah Sharma,sarahsharma1975@company.com,+1-471-298-3265,34,...,4.82,0.00,NaN,19.28,7.24,12.04,62.45,Debit Card,Diego S.,No
4,ORD-1009733,2021-01-01,2021-01-06,Standard,Mobile App,CUST-102577,Karen Miller,karen.miller24@hotmail.com,+1-308-547-5047,55,...,39.79,0.00,NaN,39.79,22.91,16.88,42.42,Credit Card,Priya C.,No

In [3]:
df.shape

(80000, 33)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        80000 non-null  str
 1   OrderDate      80000 non-null  str
 2   ShipDate       80000 non-null  str
 3   ShipMode       80000 non-null  str
 4   Channel        80000 non-null  str
 5   CustomerID     80000 non-null  str
 6   CustomerName   80000 non-null  str
 7   Email          80000 non-null  str
 8   Phone          80000 non-null  str
 9   Age            80000 non-null  int64
 10  Gender         80000 non-null  str
 11  Segment        80000 non-null  str
 12  LoyaltyTier    80000 non-null  str
 13  Region         80000 non-null  str
 14  Country        80000 non-null  str
 15  State          80000 non-null  str
 16  City           80000 non-null  str
 17  PostalCode     80000 non-null  str
 18  Category       80000 non-null  str
 19  SubCategory    80000 non-null  str
 20  ProductID      80000 non-null  str
 21  ProductName    80000 non-null  str
 22  Quantity       80000 non-null  int64
 23  UnitPrice      80000 non-null  float64
 24  Discount       80000 non-null  float64
 25  PromoCode      16886 non-null  str
 26  Sales          80000 non-null  float64
 27  Cost           80000 non-null  float64
 28  Profit         80000 non-null  float64
 29  ProfitMargin   80000 non-null  float64
 30  PaymentMethod  80000 non-null  str
 31  SalesRep       80000 non-null  str
 32  Returned       80000 non-null  str
dtypes: float64(6), int64(2), str(25)
memory usage: 37.8 MB

In [5]:
df.columns

Index(['OrderID', 'OrderDate', 'ShipDate', 'ShipMode', 'Channel', 'CustomerID',
       'CustomerName', 'Email', 'Phone', 'Age', 'Gender', 'Segment',
       'LoyaltyTier', 'Region', 'Country', 'State', 'City', 'PostalCode',
       'Category', 'SubCategory', 'ProductID', 'ProductName', 'Quantity',
       'UnitPrice', 'Discount', 'PromoCode', 'Sales', 'Cost', 'Profit',
       'ProfitMargin', 'PaymentMethod', 'SalesRep', 'Returned'],
      dtype='str')

In [6]:
df.isnull().sum()

OrderID              0
OrderDate            0
ShipDate             0
ShipMode             0
Channel              0
CustomerID           0
CustomerName         0
Email                0
Phone                0
Age                  0
Gender               0
Segment              0
LoyaltyTier          0
Region               0
Country              0
State                0
City                 0
PostalCode           0
Category             0
SubCategory          0
ProductID            0
ProductName          0
Quantity             0
UnitPrice            0
Discount             0
PromoCode        63114
Sales                0
Cost                 0
Profit               0
ProfitMargin         0
PaymentMethod        0
SalesRep             0
Returned             0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.dtypes

OrderID              str
OrderDate            str
ShipDate             str
ShipMode             str
Channel              str
CustomerID           str
CustomerName         str
Email                str
Phone                str
Age                int64
Gender               str
Segment              str
LoyaltyTier          str
Region               str
Country              str
State                str
City                 str
PostalCode           str
Category             str
SubCategory          str
ProductID            str
ProductName          str
Quantity           int64
UnitPrice        float64
Discount         float64
PromoCode            str
Sales            float64
Cost             float64
Profit           float64
ProfitMargin     float64
PaymentMethod        str
SalesRep             str
Returned             str
dtype: object

In [9]:
df.drop_duplicates()

,OrderID,OrderDate,ShipDate,ShipMode,Channel,CustomerID,CustomerName,Email,Phone,Age,...,UnitPrice,Discount,PromoCode,Sales,Cost,Profit,ProfitMargin,PaymentMethod,SalesRep,Returned
0,ORD-1005371,2021-01-01,2021-01-06,Standard,Phone Order,CUST-104055,Chloe Nguyen,chloe.nguyen5@outlook.com,+1-727-573-1855,51,...,130.75,0.05,NEWYEAR,993.70,577.76,415.94,41.86,Debit Card,Jessica A.,No
1,ORD-1005791,2021-01-01,2021-01-07,Standard,Online,CUST-101234,Richard Gonzalez,richard.gonzalez57@hotmail.com,+1-647-352-2293,40,...,185.55,0.15,NEWYEAR,157.72,130.39,27.33,17.33,Apple Pay,Ananya D.,No
2,ORD-1008078,2021-01-01,2021-01-07,Standard,Phone Order,CUST-105358,Barbara Smith,barbara.smith1996@proton.me,+1-500-343-1036,56,...,40.12,0.00,NaN,40.12,19.63,20.49,51.07,Debit Card,Liam C.,No
3,ORD-1009062,2021-01-01,2021-01-08,Standard,Phone Order,CUST-103845,Sarah Sharma,sarahsharma1975@company.com,+1-471-298-3265,34,...,4.82,0.00,NaN,19.28,7.24,12.04,62.45,Debit Card,Diego S.,No
4,ORD-1009733,2021-01-01,2021-01-06,Standard,Mobile App,CUST-102577,Karen Miller,karen.miller24@hotmail.com,+1-308-547-5047,55,...,39.79,0.00,NaN,39.79,22.91,16.88,42.42,Credit Card,Priya C.,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,ORD-1075253,2024-12-31,2025-01-06,Standard,Online,CUST-104168,Lucia Torres,luciatorres34@icloud.com,+1-647-738-8379,30,...,16.65,0.25,NEWYEAR,12.49,8.76,3.73,29.86,Debit Card,Lucia O.,No
79996,ORD-1075404,2024-12-31,2025-01-05,Standard,Online,CUST-102055,Ananya Brown,ananya.brown@company.com,+1-316-970-8538,29,...,34.51,0.20,NaN,276.08,210.00,66.08,23.94,Debit Card,Yuki J.,No
79997,ORD-1075697,2024-12-31,2025-01-07,Standard,Mobile App,CUST-100623,William Garcia,williamgarcia4@hotmail.com,+1-984-487-4610,64,...,35.63,0.05,FREESHIP,33.85,25.44,8.41,24.84,Apple Pay,Jennifer O.,No
79998,ORD-1077367,2024-12-31,2024-12-31,Same Day,In-Store,CUST-105331,Ethan Martinez,ethan.martinez@proton.me,+1-459-494-2044,51,...,73.36,0.15,BLACKFRIDAY,187.07,111.36,75.71,40.47,Apple Pay,Priya C.,No
79999,ORD-1078750,2024-12-31,2025-01-07,Standard,Online,CUST-105367,Diego Lopez,diegolopez1995@outlook.com,+1-819-374-9573,55,...,44.53,0.00,NaN,445.30,235.80,209.50,47.05,PayPal,Diego S.,Yes

In [10]:
df["Segment"].unique()

<ArrowStringArray>
['Corporate', 'Consumer', 'Home Office']
Length: 3, dtype: str

In [11]:
df["Category"].unique()

<ArrowStringArray>
['Sports & Outdoors', 'Technology', 'Office Supplies', 'Furniture',
 'Clothing']
Length: 5, dtype: str

In [12]:
df["Returned"].unique()

<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

In [13]:
df["Region"].unique()

<ArrowStringArray>
[           'Asia-Pacific', 'North America - Central',
    'North America - West',    'North America - East',
                  'Europe']
Length: 5, dtype: str

In [14]:
df.isnull().sum()

OrderID              0
OrderDate            0
ShipDate             0
ShipMode             0
Channel              0
CustomerID           0
CustomerName         0
Email                0
Phone                0
Age                  0
Gender               0
Segment              0
LoyaltyTier          0
Region               0
Country              0
State                0
City                 0
PostalCode           0
Category             0
SubCategory          0
ProductID            0
ProductName          0
Quantity             0
UnitPrice            0
Discount             0
PromoCode        63114
Sales                0
Cost                 0
Profit               0
ProfitMargin         0
PaymentMethod        0
SalesRep             0
Returned             0
dtype: int64

In [15]:
df.columns

Index(['OrderID', 'OrderDate', 'ShipDate', 'ShipMode', 'Channel', 'CustomerID',
       'CustomerName', 'Email', 'Phone', 'Age', 'Gender', 'Segment',
       'LoyaltyTier', 'Region', 'Country', 'State', 'City', 'PostalCode',
       'Category', 'SubCategory', 'ProductID', 'ProductName', 'Quantity',
       'UnitPrice', 'Discount', 'PromoCode', 'Sales', 'Cost', 'Profit',
       'ProfitMargin', 'PaymentMethod', 'SalesRep', 'Returned'],
      dtype='str')

In [16]:
df.OrderDate

0        2021-01-01
1        2021-01-01
2        2021-01-01
3        2021-01-01
4        2021-01-01
            ...
79995    2024-12-31
79996    2024-12-31
79997    2024-12-31
79998    2024-12-31
79999    2024-12-31
Name: OrderDate, Length: 80000, dtype: str

In [17]:
df.ShipDate

0        2021-01-06
1        2021-01-07
2        2021-01-07
3        2021-01-08
4        2021-01-06
            ...
79995    2025-01-06
79996    2025-01-05
79997    2025-01-07
79998    2024-12-31
79999    2025-01-07
Name: ShipDate, Length: 80000, dtype: str

In [18]:
df["ShipDate"].duplicated().sum()

np.int64(78532)

In [19]:
df["ShipDate"].duplicated()

0        False
1        False
2         True
3        False
4         True
         ...
79995     True
79996     True
79997     True
79998     True
79999     True
Name: ShipDate, Length: 80000, dtype: bool

In [20]:
df["OrderDate"].duplicated()

0        False
1         True
2         True
3         True
4         True
         ...
79995     True
79996     True
79997     True
79998     True
79999     True
Name: OrderDate, Length: 80000, dtype: bool

In [21]:
df["PromoCode"] = df["PromoCode"].fillna("No promo")

In [22]:
df["PromoCode"].isnull().sum()

np.int64(0)

In [23]:
df["Segment"] = df["Segment"].str.strip().str.title()
df["Category"] = df["Category"].str.strip().str.title()
df["Region"] = df["Region"].str.strip().str.title()
df["Returned"] = df["Returned"].str.strip().str.capitalize()

In [24]:
df[["OrderDate" , "ShipDate"]].dtypes

OrderDate    str
ShipDate     str
dtype: object

In [25]:
df[["UnitPrice", "Sales", "Cost", "Profit"]].head()

   UnitPrice   Sales    Cost  Profit
0     130.75  993.70  577.76  415.94
1     185.55  157.72  130.39   27.33
2      40.12   40.12   19.63   20.49
3       4.82   19.28    7.24   12.04
4      39.79   39.79   22.91   16.88

In [26]:
df["Returned"].unique()

<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

In [27]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"])
df["ShipDate"] = pd.to_datetime(df["ShipDate"])

In [28]:
df["OrderDate"] = df["OrderDate"].dt.strftime("%y-%m-%d")
df["ShipDate"] = df["ShipDate"].dt.strftime("%y-%m-%d")

In [29]:
df.to_csv("retail_sales_clean.csv", index=False)

In [30]:
df = pd.read_csv("retail_sales_clean.csv")

In [31]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"])

C:\Users\HP\AppData\Local\Temp\ipykernel_6328\3991573040.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["OrderDate"] = pd.to_datetime(df["OrderDate"])

In [32]:
df["Year"] = df["OrderDate"].dt.year
df["Month"] = df["OrderDate"].dt.month_name()

In [33]:
monthly_sales = df.groupby("Month")["Sales"].sum()
monthly_sales

Month
April        1931939.72
August       2120165.43
December     5642203.76
February     1861444.96
January      2199227.86
July         2210162.71
June         2134355.53
March        2164945.42
May          2191385.29
November     5405578.69
October      2187344.90
September    2037308.12
Name: Sales, dtype: float64

In [34]:
region_sales = df.groupby("Region")[["Sales", "Profit"]].sum()

region_sales

                              Sales      Profit
Region
Asia-Pacific             6427739.48  1867876.77
Europe                   6507017.00  1903391.75
North America - Central  6233644.24  1834670.44
North America - East     6533700.59  1931001.79
North America - West     6383961.08  1880199.28

In [35]:
category_sales = df.groupby("Category")[["Sales", "Profit"]].sum()

category_sales

                         Sales      Profit
Category
Clothing            2703476.46  1149717.21
Furniture           8272681.62  2502838.90
Office Supplies      762159.85   343441.35
Sports & Outdoors   2874805.21  1038090.97
Technology         17472939.25  4383051.60

In [36]:
subcategory_sales = df.groupby("SubCategory")[["Sales", "Profit"]].sum()

subcategory_sales

                  Sales      Profit
SubCategory
Accessories   355705.32   175296.03
Art           147224.95    65950.67
Binders        87573.09    47223.02
Bookcases    2044836.53   670874.13
Camping      1682745.21   572779.24
Chairs       1487838.29   475008.27
Cycling       559797.46   228126.45
Fitness       632262.54   237185.28
Footwear      938599.24   378201.65
Furnishings   708152.85   281206.12
Kids          431573.12   195413.73
Laptops      7849851.12  1702739.12
Men           633820.21   275810.32
Monitors     1737193.92   504021.28
Networking   1014569.70   364432.50
Paper         116662.12    56293.29
Pens           49711.90    29151.47
Printers     1428694.77   438920.44
Smartphones  5086924.42  1197642.23
Storage       360987.79   144822.90
Tables       4031853.95  1075750.38
Women         699483.89   300291.51

In [37]:
yearly_sales = df.groupby("Year")["Sales"].sum()

yearly_sales

Year
2001    1053978.19
2002    1001478.68
2003    1079266.80
2004    1076348.52
2005    1218439.08
2006    1098678.91
2007    1066843.91
2008    1167151.84
2009    1120637.31
2010    1054727.65
2011    1015778.00
2012    1050321.13
2013    1040918.97
2014    1144464.24
2015    1108079.23
2016    1032579.56
2017    1096919.06
2018    1028256.56
2019    1025682.20
2020    1009818.11
2021    1039287.08
2022    1072399.86
2023    1053556.02
2024    1049826.31
2025    1073983.97
2026    1086853.53
2027    1100817.48
2028    1109200.06
2029     768873.11
2030     701352.18
2031     539544.84
Name: Sales, dtype: float64

In [38]:
growth = yearly_sales.pct_change() * 100

growth

Year
2001          NaN
2002    -4.981081
2003     7.767327
2004    -0.270395
2005    13.201166
2006    -9.828983
2007    -2.897571
2008     9.402306
2009    -3.985302
2010    -5.881444
2011    -3.692863
2012     3.400657
2013    -0.895170
2014     9.947486
2015    -3.179218
2016    -6.813562
2017     6.230948
2018    -6.259578
2019    -0.250362
2020    -1.546687
2021     2.918245
2022     3.186105
2023    -1.757165
2024    -0.354012
2025     2.301110
2026     1.198301
2027     1.284805
2028     0.761487
2029   -30.682197
2030    -8.781804
2031   -23.070769
Name: Sales, dtype: float64

In [39]:
revenue = df["Sales"].sum()

print(revenue)

32086062.39

In [40]:
profit = df["Profit"].sum()

print(profit)

9417140.030000001

In [41]:
profit_margin = (profit / revenue) * 100

print(profit_margin)

29.349628245237607

In [42]:
aov = revenue / df["OrderID"].nunique()

print(aov)

401.075779875

In [43]:
top_customers = (
    df.groupby("CustomerName")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_customers

CustomerName
Linda Hernandez    65371.28
James Wilson       64102.85
Noah Brown         62408.51
Linda Martinez     61525.28
Thomas Tanaka      60230.78
William Costa      59843.27
Ananya Jones       59686.53
Lucas Chen         58255.38
Jennifer Cohen     57517.97
Sofia Reyes        57374.76
Name: Sales, dtype: float64

In [44]:
return_rate = (
    (df["Returned"] == "Yes").mean()
) * 100

print(return_rate)

4.12875

In [45]:
monthly_sales = df.groupby(df["OrderDate"].dt.to_period("M"))["Sales"].sum()

monthly_sales

OrderDate
2001-01    55662.02
2001-02    68180.49
2001-03    66341.99
2001-04    58641.29
2001-05    59680.27
             ...
2031-05    66461.68
2031-07    82298.92
2031-08    88116.04
2031-10    62617.26
2031-12    95428.85
Freq: M, Name: Sales, Length: 366, dtype: float64

In [46]:
monthly_sales.index = monthly_sales.index.to_timestamp()

In [47]:
import plotly.express as px

In [48]:
import plotly.io as pio

pio.renderers.default = "notebook"

In [49]:
import plotly.io as pio

pio.renderers.default = "vscode"

In [50]:
import plotly.express as px

df["OrderDate"] = pd.to_datetime(df["OrderDate"])

monthly_sales = df.groupby(df["OrderDate"].dt.to_period("M"))["Sales"].sum()

monthly_sales.index = monthly_sales.index.to_timestamp()

fig = px.line(
    x=monthly_sales.index,
    y=monthly_sales.values,
    labels={"x": "Month", "y": "Sales"},
    title="Monthly Sales Trend"
)

fig.show()

In [51]:
region_analysis = df.groupby("Region")[["Sales", "Profit"]].sum().reset_index()

region_analysis

                    Region       Sales      Profit
0             Asia-Pacific  6427739.48  1867876.77
1                   Europe  6507017.00  1903391.75
2  North America - Central  6233644.24  1834670.44
3     North America - East  6533700.59  1931001.79
4     North America - West  6383961.08  1880199.28

In [52]:
fig = px.bar(
    region_analysis,
    x="Region",
    y=["Sales", "Profit"],
    barmode="group",
    title="Sales and Profit by Region"
)

fig.show()

In [53]:
category_analysis = df.groupby("Category")["Sales"].sum().reset_index()

category_analysis

            Category        Sales
0           Clothing   2703476.46
1          Furniture   8272681.62
2    Office Supplies    762159.85
3  Sports & Outdoors   2874805.21
4         Technology  17472939.25

In [54]:
fig = px.pie(
    category_analysis,
    names="Category",
    values="Sales",
    title="Sales Distribution by Category"
)

fig.show()

In [55]:
top_customers = (
    df.groupby("CustomerName")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

top_customers

      CustomerName     Sales
0  Linda Hernandez  65371.28
1     James Wilson  64102.85
2       Noah Brown  62408.51
3   Linda Martinez  61525.28
4    Thomas Tanaka  60230.78
5    William Costa  59843.27
6     Ananya Jones  59686.53
7       Lucas Chen  58255.38
8   Jennifer Cohen  57517.97
9      Sofia Reyes  57374.76

In [56]:
fig = px.bar(
    top_customers,
    x="CustomerName",
    y="Sales",
    title="Top 10 Customers"
)

fig.show()

In [ ]:
yearly_sales = df.groupby("Year")["Sales"].sum().reset_index()

yearly_sales

    Year       Sales
0   2001  1053978.19
1   2002  1001478.68
2   2003  1079266.80
3   2004  1076348.52
4   2005  1218439.08
5   2006  1098678.91
6   2007  1066843.91
7   2008  1167151.84
8   2009  1120637.31
9   2010  1054727.65
10  2011  1015778.00
11  2012  1050321.13
12  2013  1040918.97
13  2014  1144464.24
14  2015  1108079.23
15  2016  1032579.56
16  2017  1096919.06
17  2018  1028256.56
18  2019  1025682.20
19  2020  1009818.11
20  2021  1039287.08
21  2022  1072399.86
22  2023  1053556.02
23  2024  1049826.31
24  2025  1073983.97
25  2026  1086853.53
26  2027  1100817.48
27  2028  1109200.06
28  2029   768873.11
29  2030   701352.18
30  2031   539544.84

In [58]:
fig = px.line(
    yearly_sales,
    x="Year",
    y="Sales",
    markers=True,
    title="Year-over-Year Sales Growth"
)

fig.show()

In [59]:
subcategory_analysis = (
    df.groupby("SubCategory")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

fig = px.bar(
    subcategory_analysis,
    x="SubCategory",
    y="Sales",
    title="Sales by SubCategory"
)

fig.show()